[package]
authors = ["gpdionisio"]
name = "week_04-padding_oracle"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
itertools = "0.10.3"
reqwest = {version = "0.11.10", features = ["blocking"]}
